### ISSUE TITLE
PR1040の `/kinect_head/depth_registered/points` が取得できない

### ISSUE THREAD

**Issue by takayuki5168** [jsk-ros-pkg/jsk_robot#1016]
PR1040で `sudo initctl restart robot` や  `sudo initctl restart jsk-pr2-startup` や `sudo pr2-shutdown --reboot` 等を何度かやってみたのですが、 `/kinect_head/depth_registered/points` が取得できません。

Kinectの赤外線発行部も赤く光っておりません。

**Comment by furushchev** [comment]
`lsusb`してデバイスを認識しているか確認してみるとどうだろう．
kinectのドライバが起動するのは`jsk-pr2-startup`がstartするタイミングなので，なにかエラーがある場合は`/var/log/upstart/jsk-pr2-startup.log`に表示されることになります．
`sudo less /var/log/upstart/jsk-pr2-startup.log`で見られますが，ぱっと見エラーは出ていない気がするので，ハードウェアと両面から確認してみてください．

**Comment by takayuki5168** [comment]
ありがとうございます。

以下の結果になったのでデバイスの認識はできてそうです。実際KinectのRGB画像なら取得出来ているので。
```sh
$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 007: ID 045e:02ae Microsoft Corp. Xbox NUI Camera
Bus 001 Device 005: ID 045e:02b0 Microsoft Corp. Xbox NUI Motor
Bus 001 Device 006: ID 045e:02ad Microsoft Corp. Xbox NUI Audio
Bus 001 Device 003: ID 0409:005a NEC Corp. HighSpeed Hub
Bus 001 Device 002: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
Bus 001 Device 004: ID 046d:0a04 Logitech, Inc. V20 portable speakers (USB powered)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by furushchev** [comment]
@takayuki5168 こちらどうなったでしょうか？僕が今見た所，直ったように思います．確認してみてください．

**Comment by takayuki5168** [comment]
@furushchev ありがとうございます、閉じます
