### ISSUE TITLE
[pr1040] respeaker node does not start

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_robot#1060]
USB connector is not good.
we need to redesign the attachment

**Comment by k-okada** [comment]
where is the cad data?
we should put them in
https://github.com/jsk-ros-pkg/jsk_robot/tree/master/jsk_pr2_robot/jsk_pr2_accessories
--
◉ Kei Okada



2019年4月19日(金) 3:16 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
I add more information about this issue.
this issue happens because USB connecter in ReSpeaker mic got loose.
Current attachment CAD is in Google team drive.
Should I manage it in github?

**Comment by k-okada** [comment]
> Should I manage it in github?

yes
--
◉ Kei Okada

2019年4月19日(金) 12:22 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
OK i will upload all CAD data.

**Comment by knorth55** [comment]
I upload all cad data https://github.com/jsk-ros-pkg/jsk_robot/pull/1064

**Comment by knorth55** [comment]
if this issue happens, please open this issues again.
