### ISSUE TITLE
[fetch1075] E-Stopが取れてる

### ISSUE THREAD

**Issue by sktometometo** [jsk-ros-pkg/jsk_robot#1566]
直す

![PXL_20220822_023912336](https://user-images.githubusercontent.com/9410362/185831186-6d275066-db1a-4899-a5ec-d5cfd27856d0.jpg)

**Comment by knorth55** [comment]
写真を貼って、修理スライドを作りましょう

**Comment by sktometometo** [comment]
修復された
https://docs.google.com/presentation/d/1wj957JB4Sv91r2vos4e-AoBlW8v0rwJl3VFARz57d_w/edit?usp=sharing

**Comment by knorth55** [comment]
ありがとうございます！
