### ISSUE TITLE
[fetch1075] FetchのTweetがおかしい

### ISSUE THREAD

**Issue by sktometometo** [jsk-ros-pkg/jsk_robot#1580]
Fetch1075のTweetがBase64 encodingされた何かっぽいんですが、これは何かのデバック中ですか?

![キャプチャ](https://user-images.githubusercontent.com/9410362/187808587-7a3ebddc-032a-476e-b5b0-1eb06032012b.PNG)

**Comment by sktometometo** [comment]
09:30のキッチンデモのDockのタイミングくらいでtweetされてる。

**Comment by tkmtnt7000** [comment]
昨日あたりまでは正常にツイートできていそうだったのでおかしいですね。。。午後に確認してみます。

**Comment by sktometometo** [comment]
8/30 にも起きてる。ここ数週間たまにこんな感じで荒ぶっている気がします。最近何かTweet周りいじられてる?

![キャプチャ](https://user-images.githubusercontent.com/9410362/187809344-9cfeb851-02fb-41f5-80d6-ab3e97884661.PNG)

**Comment by sktometometo** [comment]
8/29 にも。 8/31がたまたま起きなかった?
![キャプチャ](https://user-images.githubusercontent.com/9410362/187809491-e69b5e4b-ca0e-4ff9-b121-4a312aa7392c.PNG)

**Comment by tkmtnt7000** [comment]
僕が最近やっているsmachから通知を行うためにrostwitterを変更していて，ツイートにBase64をを直接送れるようにしています．本来は，画像に変換されて出力されるようにしています．

**Comment by sktometometo** [comment]
了解です、なるほど。

**Comment by tkmtnt7000** [comment]
該当となるPRをリンクさせておきます．https://github.com/knorth55/jsk_3rdparty/pull/31，https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/375

**Comment by sktometometo** [comment]
RSJあるので来週以降とかにやりましょう

**Comment by tkmtnt7000** [comment]
はい．ちょっと待ち時間がある作業をしたときに確認したのですが，
`[ERROR] [1661819674.539695] [/tweet:rosout]: Incorrect padding`
おそらくこのエラーが原因と考えています．
base64から画像に変換する際に正しくdecodeできていないことから発生しているようです．
ログ：全体　https://drive.google.com/file/d/10pi7y2w1XHbQrtCz_76kXcFwHnA9k0-E/view?usp=sharing

**Comment by iory** [comment]
@tkmtnt7000 
base64のパースで空白で区切ってもらうという前提を設けました。
こちらのPRで修正しました。
https://github.com/knorth55/jsk_3rdparty/pull/32
https://github.com/tkmtnt7000/jsk_robot/pull/8

**Comment by sktometometo** [comment]
Seems to be fixed.
