### ISSUE TITLE
[PR1012] サーボをONにしても背中のPowerBoardの一番上のリレーが光らない

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_robot#1637]
サーボをONにしても背中のPowerBoardの一番上のリレーが光らない
エラーコード的に電流がトリップしている？

cc. @708yamaguchi @iory

**Comment by 708yamaguchi** [comment]
修理ログです
https://docs.google.com/presentation/d/1HZCW6Uzgz049ZIq_esOZq4hz09c4yZ3r7nTiZm1CItY/edit#slide=id.p

**Comment by knorth55** [comment]
購入していたPowerBoardの新品に変更したところ，サーボが問題なくつくようになった．
もともと取り付けられていてPowerBoardにはホコリがたまっていた．
原因不明なのとPR1040でも起こりうるので原因究明と修理をしておいたほうがいい気がする．．．

**Comment by knorth55** [comment]
元のPowerBoardを掃除して戻してみたか，改善されなかった．
またケーブルが悪いかもしれないと電源の指し口を変更したが，一番上のリレーが光らなかったため，PowerBoardの問題である可能性が高い．
新しいPowerBoardにpr1012は変更して，問題なくサーボが入り動くことを確認した．
