### ISSUE TITLE
[Spot] Subscribed rate of images is very low via Sanshiro

### ISSUE THREAD

**Issue by sktometometo** [jsk-ros-pkg/jsk_robot#1779]
Via sanshiro, image rate of BelKa is extremely low. With this, we cannot generate point cloud with `depth_image_proc`.

```bash
$ rostopic hz /spot/camera/hand_color/image
subscribed to [/spot/camera/hand_color/image]
no new messages
no new messages
average rate: 1.190
	min: 0.840s max: 0.840s std dev: 0.00000s window: 2
no new messages
no new messages
no new messages
no new messages
average rate: 0.343
	min: 0.840s max: 4.996s std dev: 2.07783s window: 3
```

**Comment by knorth55** [comment]
how about compressed?

**Comment by sktometometo** [comment]
There is no compressed image topic for spot since the images are not published via image_transport.

**Comment by k-okada** [comment]
please use compressed image
--
◉ Kei Okada



2023年3月9日(木) 11:41 Koki Shinjo ***@***.***>:

**Comment by k-okada** [comment]
please add to
https://github.com/k-okada/jsk_robot/blob/spot_arm/jsk_spot_robot/jsk_spot_startup/launch/include/driver.launch#L75-L90
--
◉ Kei Okada



2023年3月9日(木) 11:44 Koki Shinjo ***@***.***>:

**Comment by sktometometo** [comment]
I don't know why, but fixed.

```
$ rostopic hz /spot/camera/hand_color/image
subscribed to [/spot/camera/hand_color/image]
average rate: 4.426
	min: 0.191s max: 0.261s std dev: 0.03498s window: 3
average rate: 6.507
	min: 0.106s max: 0.261s std dev: 0.04319s window: 11
average rate: 6.978
	min: 0.106s max: 0.261s std dev: 0.03511s window: 19
```
