### ISSUE TITLE
baxter twitterのactive timeのカウントが違う

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_robot#199]
baxter twitterが１０分米にしゃべっていますが，これは時刻的に１０分ではなくて，
ロボットが動いている時間が１０分で，その動いているというのはPR2だと
移動距離と手の関節の移動量がある程度大きい場合，みたいにしていたとおもいます．
ちゃんと使っていると，反応する，というのがいいとおもいます．

https://github.com/jsk-ros-pkg/jsk_robot/blob/34fda240ba94ee6c71a5996d8d71a241c70af8e8/jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/active_user.l
https://github.com/jsk-ros-pkg/jsk_robot/blob/fb3ee352eb9e821d951cc069beb5a6d576f80826/jsk_pr2_startup/jsk_pr2_lifelog/tweet_client.l#L110

**Comment by aginika** [comment]
腕が動いている間だけ、elapsed_timeが増えることは確認しました。
問題なければcloseおねがいします。
