### ISSUE TITLE
failed wstool update in jsk_pepper_robot/setup environment

### ISSUE THREAD

**Issue by kakehashi** [jsk-ros-pkg/jsk_robot#215]
Hi, @kochigami  and I were doing the operations in https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_pepper_robot/README.md

```
mkdir -p catkin_ws/src
cd  catkin_ws/src
```
The operations above made ~/catkin_ws/src/src directory, so we've deleted it first by $ rm -r ~/catkin_ws/src/src and then by using GUI (which means throwing the src-folder into the trash).
Then we continued 
```
wstool init src
wstool merge -t src https://raw.githubusercontent.com/jsk-ros-pkg/jsk_robot/mas\
ter/jsk_pepper_robot/pepper.rosinstall
wstool update -t src
```
and got the error messages below
```
leus@mirai1:~/catkin_ws$ wstool update -t src
[naoqi_bridge] Updating /home/leus/catkin_ws/src/naoqi_bridge
[naoqi_bridge] Done.
[nao_interaction] Fetching /home/leus/catkin_ws/src/https/github.com/ros-naoqi/nao_interaction.git (version master) to /home/leus/catkin_ws/src/nao_interaction
fatal: repository '/home/leus/catkin_ws/src/https/github.com/ros-naoqi/nao_interaction.git' does not exist
[nao_robot] Updating /home/leus/catkin_ws/src/nao_robot
[nao_robot] Done.
[jsk_robot] Updating /home/leus/catkin_ws/src/jsk_robot
Submodule '.travis' () registered for path '.travis'

[jsk_robot] Done.
Exception caught during install: Error processing 'nao_interaction' : [nao_interaction] Checkout of /home/leus/catkin_ws/src/https/github.com/ros-naoqi/nao_interaction.git version master into /home/leus/catkin_ws/src/nao_interaction failed.

ERROR in config: Error processing 'nao_interaction' : [nao_interaction] Checkout of /home/leus/catkin_ws/src/https/github.com/ros-naoqi/nao_interaction.git version master into /home/leus/catkin_ws/src/nao_interaction failed.
```
The situation looks a bit like https://github.com/start-jsk/2014-semi/issues/21, but we've already set ssh keys.

Please help us!!!

**Comment by OTL** [comment]
This patch will solve this problem!

https://github.com/jsk-ros-pkg/jsk_robot/pull/248

**Comment by furushchev** [comment]
@kakehashi Any update? If this problem was already solved, please close this issue.

**Comment by kochigami** [comment]
Hi, I know it's not my place to say this and I don't have the permission, but I think it's ok to close.

Current pepper.rosinstall is used to pick only ```jsk_robot``` .
