### ISSUE TITLE
About PR2 tilt self filter behavior

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_robot#229]
/tilt_scan_shadow_filter (topic) -> /tilt_laser_self_filter (node) ->/tilt_scan_filtered (topic)

In this flow, I expected that the /tilt_laser_sefl_filter just filter the self filter, it actually works for self filter, but it seems to filter remote or higher point clouds  too. How can I change this behavior? from parmas?

Odded-numbered image is tilt_scan_shadow_filter and 
evened-numbered image is tilt_scan_filtered.

![screenshot_from_2015-01-04 15 51 16](https://cloud.githubusercontent.com/assets/3803922/5605070/b98041f8-942a-11e4-8c65-a59bff2f1743.png)
![screenshot_from_2015-01-04 15 52 35](https://cloud.githubusercontent.com/assets/3803922/5605072/b9852484-942a-11e4-92d9-d003b7fa4dfd.png)
![screenshot_from_2015-01-04 15 53 26](https://cloud.githubusercontent.com/assets/3803922/5605071/b984fc2a-942a-11e4-86c8-093d4cdc3009.png)
![screenshot_from_2015-01-04 15 53 50](https://cloud.githubusercontent.com/assets/3803922/5605073/b985b124-942a-11e4-9b29-4e7342b5e696.png)

**Comment by garaemon** [comment]
The parameters are written in yaml file

2015年1月4日日曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> /tilt_scan_shadow_filter (topic) -> /tilt_laser_self_filter (node)
> ->/tilt_scan_filtered (topic)
>
> In this flow, I expected that the /tilt_laser_sefl_filter just filter the
> self filter, it actually works for self filter, but it seems to filter
> remote or higher point clouds too. How can I change this behavior? from
> parmas?
>
> Odded-numbered image is tilt_scan_shadow_filter and
> evened-numbered image is tilt_scan_filtered.
>
> [image: screenshot_from_2015-01-04 15 51 16]
> <https://cloud.githubusercontent.com/assets/3803922/5605070/b98041f8-942a-11e4-8c65-a59bff2f1743.png>
> [image: screenshot_from_2015-01-04 15 52 35]
> <https://cloud.githubusercontent.com/assets/3803922/5605072/b9852484-942a-11e4-92d9-d003b7fa4dfd.png>
> [image: screenshot_from_2015-01-04 15 53 26]
> <https://cloud.githubusercontent.com/assets/3803922/5605071/b984fc2a-942a-11e4-86c8-093d4cdc3009.png>
> [image: screenshot_from_2015-01-04 15 53 50]
> <https://cloud.githubusercontent.com/assets/3803922/5605073/b985b124-942a-11e4-9b29-4e7342b5e696.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_robot/issues/229>.
>


-- 
from iPhone

**Comment by aginika** [comment]
We couldn't find out the parameter which seems to change the odd output of the self_filter.

**Comment by garaemon** [comment]
Please use original parameter with new self filter setting.

✉︎ Ryohei

**Comment by aginika** [comment]
Thank you very much!

**Comment by aginika** [comment]
Solved with #233
