### ISSUE TITLE
Make the tilt_scan processing chain cleaner.

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_robot#241]
Now, as far as I searched, I think the tilt_scan processing is below.
![tilt_laser_chain](https://cloud.githubusercontent.com/assets/3803922/5709061/c8b2bdbc-9ad9-11e4-9d58-fa657e145c85.png)

I think we can change below things?

- delete /scan_to_cloud_filter_chain_tilt_laser (What is /tilt_scan_shadow2_filter?)
- delete /tilt_scan_assembler
- remove /tilt_scan from /move_base_node input or remove /ground_objectcloud_mux from /move_base_node input
- remove /sac_ground_removal because move_base_node will automatically remove with min_obstacle_height or max_obstacle_height

I know the best way to decide what to do is to try on real robot, but before that, are there any idea?

**Comment by garaemon** [comment]
> delete /scan_to_cloud_filter_chain_tilt_laser (What is /tilt_scan_shadow2_filter?)

+1
> delete /tilt_scan_assembler

-1 It provide service interface to collect scans into pointcloud.
> remove /tilt_scan from /move_base_node input or remove /ground_objectcloud_mux from /move_base_node input

why?

> remove /sac_ground_removal because move_base_node will automatically remove with min_obstacle_height or max_obstacle_height

Did you confirm that robots avoid obstacles as we expected?

**Comment by aginika** [comment]
I removed the ground_object from the costmap_common_params.yaml setting fot testing.
Then the local_costmap seems to only use base_scan... I couldn't understand why it doesn't use til_scan as costmap even though move_base_node is subscribing /tilt_scan.
![screenshot_from_2015-02-06 00 08 47](https://cloud.githubusercontent.com/assets/3803922/6062706/3340bbca-ad95-11e4-9ebb-b8677d147184.png)



```
observation_sources: base_scan_marking base_scan tilt_scan #ground_object_cloud

base_scan_marking: {sensor_frame: base_laser_link, topic: /base_scan_marking, data_type: PointCloud2, expected_update_rate: 0.2,
  observation_persistence: 0.0, marking: true, clearing: false, min_obstacle_height: 0.08, max_obstacle_height: 2.0}

base_scan: {sensor_frame: base_laser_link, topic: /base_scan, data_type: LaserScan, expected_update_rate: 0.2,
             observation_persistence: 0.0, marking: false, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0, raytrace_range: 10.0}
# Modified : extend raytrace area (10.0 m)

tilt_scan: {sensor_frame: laser_tilt_link, topic: /tilt_scan, data_type: LaserScan, expected_update_rate: 0.2,
             observation_persistence: 0.2, marking: false, clearing: true, min_obstacle_height: -20.00, max_obstacle_height: 40.0}

```

**Comment by aginika** [comment]
pr2_navigation_config's costmap_common_params,yaml's tilt_scan is subscribing /tilt_scan_interpolated.

/tilt_scan_interpolated is published from laser_and_filters.xml
```
<node pkg="laser_filters" type="scan_to_scan_filter_chain" name="interpolate_missing_tilt_laser_data_filter">
  <rosparam command="load" file="$(find pr2_navigation_perception)/config/laser_interpolation.yaml" />
  <remap from="scan" to="tilt_scan" />
  <remap from="scan_filtered" to="tilt_scan_interpolated" />
</node>
```

But our laser_and_filter.xml doesn't have this node...

**Comment by garaemon** [comment]
let's add it

**Comment by aginika** [comment]
>> delete /scan_to_cloud_filter_chain_tilt_laser (What is /tilt_scan_shadow2_filter?)
> +1
tilt_scan_shadow2_filter seemed to be used for collider input.
The collider is now set as if="false" in tilt_cloud_scan.launch.
How should I do?

If collider is not needed anymore, I think I can remove tilt_cloud_scan.launch.

**Comment by aginika** [comment]
>> remove /tilt_scan from /move_base_node input or remove /ground_objectcloud_mux from /move_base_node input

> why?

>> remove /sac_ground_removal because move_base_node will automatically remove with min_obstacle_height or max_obstacle_height

> Did you confirm that robots avoid obstacles as we expected

I misunderstood around this move_base input.
In default setting, move_base will use ground_object_removal as marker and /tilt_scan as cleaner.
So we need to use both input and we can't clean around move_base inputs.

Only cleaning point is above collider around.

**Comment by garaemon** [comment]
Is marker an obstacle?

✉︎ Ryohei Ueda




On Thu, Feb 5, 2015 at 8:22 AM -0800, "Yuto Inagaki" <notifications@github.com> wrote:














remove /tilt_scan from /move_base_node input or remove /ground_objectcloud_mux from /move_base_node input




why?




remove /sac_ground_removal because move_base_node will automatically remove with min_obstacle_height or max_obstacle_height




Did you confirm that robots avoid obstacles as we expected




I misunderstood around this move_base input.

In default setting, move_base will use ground_object_removal as marker and /tilt_scan as cleaner.

So we need to use both input and we can't clean around move_base inputs.



Only cleaning point is above collider around.

**Comment by aginika** [comment]
yes , I think
```
~<name>/<source_name>/clearing (bool, default: false)
Whether or not this observation should be used to clear out freespace.
~<name>/<source_name>/marking (bool, default: true)
Whether or not this observation should be used to mark obstacles.
```

**Comment by garaemon** [comment]
Could you update the picture of move_base pipilene? and add it to README.md

✉︎ Ryohei Ueda




On Thu, Feb 5, 2015 at 2:51 PM -0800, "Yuto Inagaki" <notifications@github.com> wrote:












yes , I think

~<name>/<source_name>/clearing (bool, default: false)
Whether or not this observation should be used to clear out freespace.
~<name>/<source_name>/marking (bool, default: true)
Whether or not this observation should be used to mark obstacles.

**Comment by aginika** [comment]
Sure, I will.
I will remove collider related topics and send Pull Request.
After that I will send PR about updating README
