### ISSUE TITLE
jsk_robot doc path correct?

### ISSUE THREAD

**Issue by 130s** [jsk-ros-pkg/jsk_robot#258]
[hydro rosdistro list](https://github.com/ros/rosdistro/blob/fe60ef6d1b3d035047327f6de3fbe5a85458e515/hydro/distribution.yaml#L3136) says `https://github.com/tork-a/jsk_robot-release.git`. [Source path was fixed earlier](https://github.com/ros/rosdistro/pull/6866), but doc path remains pointing to its release repository. 

This prevents doc from being generated at http://wiki.ros.org/jsk_robot.

I've looked into the [development repository](https://github.com/jsk-ros-pkg/jsk_robot) (which is, here) but I'm not sure if the setting above is intended.

**Comment by k-okada** [comment]
thanks, fixed in https://github.com/ros/rosdistro/pull/7105

--
◉ Kei Okada
