### ISSUE TITLE
can't connect mongodb erorr about baxter.launch

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_robot#292]
I launched baxter.launch and had such error::
```sh
$ roslaunch jsk_baxter_startup baxter.launch
[ERROR] [WallTime: 1428562261.824058] MongoDB process stopped!
[ERROR] [WallTime: 1428562261.824136] Mongo process error! Exit code=100
```
What's the problem or where can I find it by reading the code?

**Comment by furushchev** [comment]
this may be because zombie process still exists.
please check

```bash
$ lsof -i:62345 # assume that mongod uses port 62345
```

And if zombie `mongod` is launched unless launching `baxter.launch`, please kill the process.:

```bash
$ sudo pkill mongod
```

then restart `baxter.launch`

**Comment by wkentaro** [comment]
It is solved. thank you!
