### ISSUE TITLE
pepper_description and pepper_bringup conflict for doc jobs

### ISSUE THREAD

**Issue by vrabaud** [jsk-ros-pkg/jsk_robot#305]
The official packages are now at:
https://github.com/ros-naoqi/
If you have anything you want to transfer, Kei has access.
Then, please remove the pepper_* packages that are not official and the doc jobs will show correctly on:
http://wiki.ros.org/pepper_bringup
Thx !

**Comment by k-okada** [comment]
I see, now it completely removed from our repo
https://github.com/jsk-ros-pkg/jsk_robot/pull/307

--
◉ Kei Okada

**Comment by vrabaud** [comment]
thx !

**Comment by chiwunau** [comment]
@k-okada sensei
Can I add ros-naoqi/pepper_robot to jsk_common/jsk.rosinstall ?
catkin build peppereus does not pass because of lack of pepper.urdf
and they don't have it if I do sudo apt-get install ros-hydro-pepper-description.

**Comment by vrabaud** [comment]
fyi, the urdf in pepper_robot is in is at: https://github.com/ros-naoqi/pepper_robot/blob/master/pepper_description/urdf/pepper1.0_generated_urdf/pepper.urdf

**Comment by k-okada** [comment]
vincent is right, and please make sure that if you use shadow-fixed repo
and if you still have problem,  paste error message for peppereus

--
◉ Kei Okada

**Comment by chiwunau** [comment]
forgot to apt-get upgrade
It works now, sorry for the trouble.

**Comment by k-okada** [comment]
please not that if you want to create papper.l file, you need to manually
install ros-%ROS_DISTRO-pepper-meshes and read license carefully, then run
catkin b peppereus again.

--
◉ Kei Okada
