### ISSUE TITLE
naoeusのパッケージについて

### ISSUE THREAD

**Issue by kochigami** [jsk-ros-pkg/jsk_robot#342]
もうすぐ未来館での見学対応があるのですが、その時にナオも動くといいかな、と思っています。
しかし、
roseus nao-interface.lを読み込んでも

/opt/ros/hydro/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: ERROR th=0  0x5fe1fb8 in (apply #'ros::load-org-for-ros ros::fullname args)E:

とエラーが出るようになってしまいました。
naoeusのパッケージに、package.xmlではなくmanifest.xmlがある（パッケージが古い）ことが原因なのでしょうか。それとも、問題はもっと深いのでしょうか。

**Comment by k-okada** [comment]
roseus
$ (load "nao-interface.l")

として見て下さい
https://github.com/jsk-ros-pkg/jsk_roseus/issues/314

2015年6月3日水曜日、Kanae Kochigami<notifications@github.com>さんは書きました:

> もうすぐ未来館での見学対応があるのですが、その時にナオも動くといいかな、と思っています。
> しかし、
> roseus nao-interface.lを読み込んでも
>
> /opt/ros/hydro/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: ERROR th=0
> 0x5fe1fb8 in (apply #'ros::load-org-for-ros ros::fullname args)E:
>
> とエラーが出るようになってしまいました。
>
> naoeusのパッケージに、package.xmlではなくmanifest.xmlがある（パッケージが古い）ことが原因なのでしょうか。それとも、問題はもっと深いのでしょうか。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_robot/issues/342>.
>


-- 
--
◉ Kei Okada

**Comment by kochigami** [comment]
ご教示ありがとうございました。
エラーの内容が読めました。

**Comment by k-okada** [comment]
なんて書いてあった？

2015年6月4日木曜日、Kanae Kochigami<notifications@github.com>さんは書きました:

> Closed #342 <https://github.com/jsk-ros-pkg/jsk_robot/issues/342>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_robot/issues/342#event-322538544>.
>


-- 
--
◉ Kei Okada

**Comment by kochigami** [comment]
```
roseus ;; loading roseus("") on euslisp((9.11 host06.storm.ros.org Thu Feb 19 15:39:45 UTC 2015  1.0.3))                                                       
eustf roseus_c_util 1.irteusgl$ load "nao-interface.l"
/opt/ros/hydro/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error:  file #P"/opt/ros/hydro/share/euscollada/nao.l" not found in (apply #'ros::load-org-for-ros ros::fullname args)
```
です。
naoeus/euslisp 以下に、昔作って取っておいてあったnao.l (improved 版)を置いておくだけでは駄目みたいで、jsk_nao_robotのREADMEにあるnao.lの作成を最初からやるとうまくいきました。
generate nao.l では点が出て（ロボットではない）、
improve nao.l ではariesに接続した状態（そこからコレオグラフをダウンロードしてくる→モデルをつくる材料にするようです）であれば、可愛いナオになることが分かりました。
