### ISSUE TITLE
naoqi のｍｓｇを更新するとき、msgファイルを更新する他に何が必要？

### ISSUE THREAD

**Issue by jiangjun0105** [jsk-ros-pkg/jsk_robot#369]
naoqi_msgs の中のBumper.msgに後ろのバンパーの情報も入れたいです、Bumper.msgのファイルを更新して、そのメッセージを使っているlaunch file を立ち上げる時、以下のエラーが出てきた。
![issue](https://cloud.githubusercontent.com/assets/8521008/8693804/df09d250-2b14-11e5-8f4f-9a50a556f23d.png)
今知りたいのは、msgを更新するとき、その　.ｍｓｇ　を更新する他に、コンパイルとかなんかやらないといけない事はありますか。
使う言語はpythonです。
よろしくお願いします。

**Comment by kochigami** [comment]
naoqi_msgsをcatkin make してみてくれますか。
気づくのが遅くなってごめんなさい！

**Comment by jiangjun0105** [comment]
やってみましたが、
```
jiangjun@jiangjun-ThinkPad-T420s:~/catkin_ws$ catkin_make --only-pkg-with-deps naoqi_msgs
Base path: /home/jiangjun/catkin_ws
Source space: /home/jiangjun/catkin_ws/src
Build space: /home/jiangjun/catkin_ws/build
Devel space: /home/jiangjun/catkin_ws/devel
Install space: /home/jiangjun/catkin_ws/install
Packages "naoqi_msgs" not found in the workspace
```
どうやって違うworkspaceのpackageをcatkin_make?

**Comment by kochigami** [comment]
naoqi_msgsがopt以下にあるということだよね…

ソースコードをとってくる以外に方法はないのか、詳しい方がいらっしゃればご教示ください。
（役に立たずごめんなさい。）

**Comment by garaemon** [comment]
nao_appsをソースで使うためには、naoqi_msgsをソースコードを取ってくるしかないと思います.

**Comment by jiangjun0105** [comment]
ごめん、ソースコードをてってくるという方法は具体的にどうやってするかは教えてもらえませんか
@kochigami

**Comment by kochigami** [comment]
授業でした。ごめんなさい。
もう解決していたらごめんなさい。

Githubのnaoqi_msgsのページからgit cloneしてください。

**Comment by jiangjun0105** [comment]
I solved it by `git clone` the source to catkin workspace.
Thank you for you help!
