### ISSUE TITLE
pr2 のroslaunch が遅い

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_robot#498]
ちゃんとhttps://github.com/ros/ros_comm/pull/682 パッチがあたっているか心配なので，

pr1012:~k-okada/work に debをおきました．
何かあっても元に戻せるので試してみて下さい．

このdebの生成スクリプトは以下
https://gist.github.com/k-okada/a1990dd4586d9f9fa819

**Comment by k-okada** [comment]
you can revert this by
sudo dpkg  -i /var/cache/apt/archives/ros-hydro-roslaunch_1.10.12-0precise-20150327-1953-+0000_amd64.deb 
the deb is also find at 
http://packages.ros.org/ros/ubuntu/pool/main/r/ros-hydro-roslaunch/

**Comment by h-kamada** [comment]
robot start　実測で 55秒から 38 秒。そこまで効果はないでしょうか。
とりあえずpr1012は入れたままにしておきます。

**Comment by garaemon** [comment]
roslaunch以外も必要という話だったりしませんか. catkin_pkgとか

**Comment by furushchev** [comment]
roslibも変える必要がありました。
@k-okada のpatchをforkして追加しました。
https://gist.github.com/furushchev/6c0e1fb3f6ecdb8b744c

**Comment by furushchev** [comment]
pr1012にpatchを当てて試して見ました。
robot startはEnterキーを押してから21秒になりました。

**Comment by k-okada** [comment]
debはどこにああるかな．バージョンは99ではなくて100にしておきましょう．後でトラック出来るように．

**Comment by furushchev** [comment]
debも上のリンクにあります。
今から100に変更します。

**Comment by furushchev** [comment]
@k-okada roslaunchとroslibのdebがあって、roslaunchに関しては前のものから変更なしですが、それでも両方100に上げますか？

**Comment by k-okada** [comment]
ああ，だったら大丈夫です．~k-okada/workにもdebを置いておきました．

--
◉ Kei Okada
