### ISSUE TITLE
Please release 1.0.2 of jsk_robot

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_robot#555]

**Comment by k-okada** [comment]
ok, done.
https://github.com/ros/rosdistro/pull/10529

It will take some time to copy to the shadow-fixed...
https://github.com/ros-infrastructure/ros_buildfarm/issues/189#issuecomment-178097767

--
◉ Kei Okada

**Comment by wkentaro** [comment]
thank you.
