### ISSUE TITLE
[naoeus, peppereus] :send-stiffness-controller :servo-on :servo-off をnaoqi-interface.lに移しても良いでしょうか．

### ISSUE THREAD

**Issue by kochigami** [jsk-ros-pkg/jsk_robot#570]
共通のメソッドが2つのプログラムで定義されています．

１．ペッパーが登場する前のナオ：:send-stiffness-controllerを使って:servo-on, offでサーボオン，サーボオフしていた
２．登場したばかりのペッパー：ナオと同じように出来ないので，wakeUp, restという関数を呼び出すように:servo-on, off をオーバーライド
３．現在：ナオもペッパーと同じようにオーバーライドになっている

ペッパーでは，:send-stiffness-controllerは，一部だけサーボオン・オフする時に使っています．
ナオも同じ使い方ができると思います．

#568 でやろうとしていること（:start-grasp, :stop-graspで手のstiffnessを変更したい）
を，naoqi-interface.l上で書きたいです．
何か勘違いしていたらすみません．

**Comment by k-okada** [comment]
はい．そうしてください．

--
◉ Kei Okada


2016-03-15 18:18 GMT+09:00 Kanae Kochigami <notifications@github.com>:

**Comment by kochigami** [comment]
ご教示ありがとうございました．

**Comment by kochigami** [comment]
> #568 でやろうとしていること（:start-grasp, :stop-graspで手のstiffnessを変更したい）
を，naoqi-interface.l上で書きたいです．

は以下のコマンドで行えるため，
```:start (stop)-grasp```メソッドを変更してstiffnessという引数を加えるのはやめました．

```
send *ri* :send-stiffness-controller :rhand (lhand) 0.5
send *ri* :start-grasp :rarm (:larm)
```
