### ISSUE TITLE
1.0.6 release, please.

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_robot#606]
## why?

I need https://github.com/jsk-ros-pkg/jsk_robot/pull/602 .

**Comment by k-okada** [comment]
Is it better to include new xacro based  baxter.l generation code to the new release?

--
◉ Kei Okada

2016/05/14 17:21、Kentaro Wada <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
Maybe it is not necessary for APC.

**Comment by furushchev** [comment]
+1 for me
currently deb of `jsk_pr2_startup` fails until #618 is released.

**Comment by k-okada** [comment]
Done

2016年6月17日金曜日、Furushchev<notifications@github.com>さんは書きました:

> +1 for me
> currently deb of jsk_pr2_startup fails until #618
> <https://github.com/jsk-ros-pkg/jsk_robot/pull/618> is released.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_robot/issues/606#issuecomment-226648778>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3GaOg1_er6NcLABjDH3wv_su9UvDks5qMeXWgaJpZM4IejbR>
> .
>


-- 
--
◉ Kei Okada
