### ISSUE TITLE
Setup Baxter robot in JSK 73B2

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_robot#634]
## TODO

- [x] Setup E-Stop
- [x] Setup Vacuum Gripper @pazeshun 
- [x] Setup Kinect2
- [x] Setup Sheeta @wkentaro

@knorth55 
@pazeshun 
@yuyu2172 
@pazeshun

**Comment by k-okada** [comment]
Use 200V cleaner and see if what will happen if we maximize the power

On Tuesday, 5 July 2016, Kentaro Wada <notifications@github.com> wrote:

> TODO
>
>    - Setup E-Stop
>    - Setup Vacuum Gripper
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_robot/issues/634>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3DN5V36utAUpzM8TmXsxeLx4kMBoks5qSfvMgaJpZM4JE0NC>
> .
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
Fixed.
