### ISSUE TITLE
[fetcheus] fetch should be :larm?

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_robot#720]
according to `pr2eus_moveit/robot-moveit.l`, I thought default arm of `angle-vector-motion-plan` should be `:larm`
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus_moveit/euslisp/robot-moveit.l#L466

**Comment by k-okada** [comment]
fetch only have rarm, defined in
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/fetcheus/fetch.yaml#L7

--
◉ Kei Okada


2016-11-11 21:46 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
ok. fetch's arm is `:rarm`. i though it should be `:larm` because default arm of `robot-moveit` is `:larm`
