### ISSUE TITLE
release request: jsk_robot_startup

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_robot#757]
I'd like to use the feature added by https://github.com/jsk-ros-pkg/jsk_robot/commit/7bd29faf47ca6e2deef4c169138998cd8794270e.
@k-okada Please release new version when you have time :dango:

**Comment by furushchev** [comment]
oh, sorry it's better to wait https://github.com/jsk-ros-pkg/jsk_robot/pull/754

**Comment by furushchev** [comment]
#754 was merged.
Need to wait for other PRs? @k-okada

**Comment by k-okada** [comment]
ok, added labels for next release https://github.com/jsk-ros-pkg/jsk_robot/milestone/3
