### ISSUE TITLE
/etc/initでroscoreが上がるスタイルのロボット運用について

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_robot#766]
今PR2のアップグレードをしていて、他のロボットを見習ってPCの起動時にroscoreが上がるスタイルにするのを検討していますが、
非`/etc/init`スタイルユーザとして質問が有ります。

nodeletをloadするときにmanagerが立ち上がっているユーザのcatkin workspaceからnodeletが引けないとload出来ない気がします。
(カメラのノードなどは`/etc/init`で上がるという前提です。)
何かworkaroundがあるのでしょうか？
あれば教えていただきたいです。

**Comment by k-okada** [comment]
わかっていないけど、
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_startup/config/install_upstart.sh
でしょうか．

--
◉ Kei Okada


2017年4月19日 13:41 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
オフラインでnodeletはカメラドライバ用と認識用でmanagerを分けていると聞いて、疑問は解決しました。
