### ISSUE TITLE
[jsk_pr2_desktop] PR2 icons are automatically added to Desktop

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_robot#786]
When I build `jsk_pr2_desktop`, `PR2` icons are automatically added by `catkin build jsk_pr2_desktop`.
This icon installation should be move to script program like `rosrun jsk_pr2_desktop install_icons.py`

![jsk_pr2_desktop](https://cloud.githubusercontent.com/assets/9300063/26770707/fda096a4-49f3-11e7-8447-a9785c1308f1.png)

**Comment by furushchev** [comment]
IMO, `jsk_pr2_startup` is built for only PR2 users, and I think it's good idea to begin with this commands to start PR2.

**Comment by knorth55** [comment]
These icons are for pr2 users only.
Those who use jsk_robot but not pr2user, i.e. baxter and fetch users do not want these.

**Comment by furushchev** [comment]
@knorth55 So why they build `jsk_pr2_startup`?

**Comment by pazeshun** [comment]
I think the following way is simplest:
make workspace -> wstool update -> rosdep install -> `catkin build`
I don't want to remember which package I should build.

**Comment by knorth55** [comment]
Because it is included in jsk_robot package.
When i clone this repo, this package is also cloned.

**Comment by knorth55** [comment]
> I think the following way is simplest:
make workspace -> wstool update -> rosdep install -> catkin build
I don't want to remember which package I should build.

What do you mean?

**Comment by furushchev** [comment]
@knorth55 @pazeshun 
So basically you build all packages in workspace? Simply `catkin build` in workspace builds all packages in the workspace including unrelated packages and takes longer time on build. You can instead simply `catkin build jsk_apc` for example to build all packages that is necessary for this package.

**Comment by furushchev** [comment]
Another possible idea is that changing desktop entry files from desktop to `~/.local/share/applications`, which is user space of menu icons.
This does not create desktop shortcuts but does menu in unity dashboard.

![unity](https://cloud.githubusercontent.com/assets/1901008/26775094/53f0ca28-4a0e-11e7-91c3-327317e130ea.png)

@k-okada How do you think of this?

**Comment by knorth55** [comment]
I always use catkin build because my workspace is not large.
I know i can build with cakin build [package].
My point is adding icons on desktop is not build but installation, i think.
