### ISSUE TITLE
PR2 1012 suddenly servo off

### ISSUE THREAD

**Issue by takayuki5168** [jsk-ros-pkg/jsk_robot#940]
PR2 1012 suddenly servo off many times from yesterday. Once suddenly servo off, servo on and off are repeated automatically speedly.

Below images are which I captured pr2 dashboard.

![pr2_was_killed2](https://user-images.githubusercontent.com/20228327/41325270-5f194bee-6ef4-11e8-9ae2-1d4600d7560d.png)
![pr2_was_killed2_all](https://user-images.githubusercontent.com/20228327/41325275-67830252-6ef4-11e8-8f7b-a0d303bc1cdc.png)

**Comment by takayuki5168** [comment]
Today, few days layer, I used PR1012 but servo didn't be off at all. So I close this issue.

If servo off again, I will reopen this issue.

**Comment by furushchev** [comment]
@takayuki5168 Thanks for report! Please watch carefully dashboard and also the output on the screen you are running `robot start` where logs related to `ethercat` or communication problem will be displayed.
