### ISSUE TITLE
PR2のグリッパーに付いているタクタイルセンサを使いたい

### ISSUE THREAD

**Issue by takayuki5168** [jsk-ros-pkg/jsk_robot#977]
[参考](http://wiki.ros.org/pr2_gripper_sensor_action) のように使うことができる

実際に使えたので後で追記します

**Comment by takayuki5168** [comment]
`pressure/r_gripper_motor` , `pressure/r_gripper_motor` トピックのそれぞれにグリッパの左右両方のタクタイルセンサ値が22個のint16のarrayでpublishされている

**Comment by takayuki5168** [comment]
[参考](http://wiki.ros.org/fingertip_pressure#view_fingertip_pressure)のように、`rosrun fingertip_pressure view_fingertip_pressure` でビジュアライズできる。

ただし、wxpython2.8が必要。ubuntu16.04での入れ方は分からず

**Comment by shmpwk** [comment]
@knorth55 
`pressure/r_gripper_motor` , `pressure/l_gripper_motor` のトピックが，グリッパを触っても常に全て0なのですが，現在は使用できないのでしょうか？

**Comment by knorth55** [comment]
現在はタクタイルセンサがついた指先ではないんじゃないかな

**Comment by shmpwk** [comment]
了解しました
