### ISSUE TITLE
[pr1012] base_scanの値がおかしい

### ISSUE THREAD

**Issue by iory** [jsk-ros-pkg/jsk_robot#981]
pr1012の```/base_scan```の値がおかしいです。
下記にrvizで表示した様子を示します。

![jsk_startup rviz- - rviz_012](https://user-images.githubusercontent.com/4690682/47628253-01f21180-db78-11e8-86a6-82c928f117a4.png)

**Comment by YutoUchimi** [comment]
台車部分のカバーはしっかりハマっているでしょうか？
乗せるだけだとレーザー部分を覆ってしまう気がします。

**Comment by iory** [comment]
なるほど。
戻ったら確認します。

**Comment by iory** [comment]
カバーを確認したところ、```base_scan```が見えるようになりました。

![image](https://user-images.githubusercontent.com/4690682/47632274-c0b82c80-db8c-11e8-97b7-e79f0caac934.png)

カバーの状態は下記の写真のようにカバーの白い部分が外側の濃い白いカバーに入っている状態が正しいようでした。

![out](https://user-images.githubusercontent.com/4690682/47632483-9450e000-db8d-11e8-8a36-544c0e076392.jpg)
